### ISSUE TITLE
[HDB-225] Abgrenzung zwischen Observation und Condition

### ISSUE THREAD

**Issue by julsas** [medizininformatik-initiative/kerndatensatzmodul-symptome#18]
Die Abgrenzung zwischen der Nutzung des Observation-Profils oder Condition-Profils ist anhand der Beschreibung im IG schwer nachzuvollziehen. Eine konkrete Handlungsempfehlung inkl. Beispiele wäre wünschenswert, um z.B. zu wissen, wann ein Phänotyp als Observation und wann als Condition abgebildet werden soll.

**Comment by beakmachine** [comment]
### In den IG einzufügen:

Conditions sind Gesundheitsstatus (wie Symptome einer Erkrankung), die von Patient:innen geäußert bzw. von Ärzt:innen zugeordnet werden. Sie werden durch einen einzelnen Code angegeben, z. B. aus der Findings-Hierarchie aus Snomed CT.

Observations sind Beobachtungen, die in der Regel von Ärzt:innen in einem diagnostischen Prozess erhoben werden, und immer aus einem Code/Werte-Paar bestehen. Mit dem Code wird angegeben, was gemessen/beobachtet wird (z. B. Herzfrequenz, Hautfarbe, Gewicht, Temperatur). Der Wert gibt den Messwert an (z. B. 80, blass, 80,5 kg, 37,0 ˚ C). Er kann  unterschiedliche Skalenniveaus annehmen und entsprechende Einheiten besitzen.

**Comment by beakmachine** [comment]
In den IG eingefügt:

Conditions sind Gesundheitsstatus (wie Symptome einer Erkrankung oder Diagnosen), die von Patient:innen geäußert bzw. von Ärzt:innen zugeordnet werden. Sie werden durch einen einzelnen Code angegeben, z. B. aus der Findings-Hierarchie aus Snomed CT.

Observations sind Beobachtungen, die in der Regel von Ärzt:innen in einem diagnostischen Prozess erhoben werden oder auch durch Sensoren gemessen werden, und immer aus einem Code/Werte-Paar bestehen. Mit dem Code wird angegeben, was gemessen/beobachtet wird (z. B. Herzfrequenz, Hautfarbe, Gewicht, Temperatur). Der Wert gibt den Messwert an (z. B. 80, blass, 80,5 kg, 37,0 ˚ C). Er kann unterschiedliche Skalenniveaus annehmen und entsprechende Einheiten besitzen.
