### ISSUE TITLE
[HDB-227] Doppelte Definition des Zeitraums im logischen Modell

### ISSUE THREAD

**Issue by alexzautke** [medizininformatik-initiative/kerndatensatzmodul-symptome#19]
Im logischen Modell für das Condition Profil ist für den klinisch relevanten Zeitraum (Spezifikation Zeitraum) der Beginn und das Ende doppelt angegeben:
Beginn: start und vonAm
Ende: end und bis
Gibt es hierfür eine Begründung oder ist dies ein Fehler innerhalb des IG?

- Einreichende Person: Elisa Henke

**Comment by julsas** [comment]
Wurde korrigiert. Lag daran, dass im Element 'Zeitspanne' die Elemente 'vonAm' und 'bis' modelliert wurden, durch Datentyp 'Period' für 'Zeitspanne' aber automatisch die Elemente 'start' und 'end' erzeugt werden.
