### ISSUE TITLE
[HDB-226] - Abgrenzung zwischen Condition-Profil des Moduls Diagnose und des Erweiterungsmoduls

### ISSUE THREAD

**Issue by alexzautke** [medizininformatik-initiative/kerndatensatzmodul-symptome#20]
Im IG für das Erweiterungsmodul wird erläutert::

Dieses Modul kann immer dann eingesetzt werden, wenn es keine spezifischen Repräsentationen in bereits vorhandenen dedizierten Modulen wie z. B. Diagnose oder Labor gibt oder wenn diese aus verschiedensten Gründen nicht anwendbar sind.
Ein Vergleich des Condition Profils des Basismoduls Diagnose mit dem des Erweiterungsmoduls hat keine wesentlichen Unterschiede aufgezeigt. Aus diesem Grund ist es schwer nachzuvollziehen, wann das Condition Profil des Erweiterungsmoduls überhaupt genutzt werden soll. Die Abgrenzung beider Profile sollte durch eine detailliertere Erläuterung inkl. Beispiele näher beschrieben werden. Insbesondere ist dies für anschließende Auswertungen in Forschungsprojekten von Bedeutung, da FHIR-Ressourcen innerhalb der MII standortübergreifend auf einer gleichen Basis spezifiziert werden sollten.

Einreichende Person: Elisa Henke

**Comment by beakmachine** [comment]
### Ergänzung in den IG einzufügen

Condition des Moduls Symptom/Phänotyp wird immer dann genutzt, wenn es sich um folgende Entitäten handelt:
1. Symptome, die vom Patienten berichtet werden (Kopfschmerz, Gewichtsverlust)
2. Symptome, die von einem Arzt bzw. einer Ärztin zugeordnet werden (Kopfschmerz, Gewichtsverlust)
3. Symptome sind in bestimmten Fällen nicht grundsätzlich von Diagnosen zu unterscheiden (Kopfschmerz); wenn es sich dabei nicht um eine Diagnose des Behandlungsfalls handelt, die bereits im Modul Diagnose kodiert ist, dann können sie in diesem Modul repräsentiert werden. Für Symptom/Diagnose Gruppen (Syndrome und Phänotypen) ist das z. B. sinnvoll.

**Comment by beakmachine** [comment]
Wir haben folgenden Text in den IG aufgenommen:

Das Modul Symptom/Phänotyp wird immer dann genutzt, wenn es (noch) kein spezifisches Modul für eine Condition bzw. Observation gibt. Das Modul Symptom/Phänoty soll dabei als ein Template für Modul-Autoren zur Modellierung von Diagnosen, Symptomen und Observations verstanden werden, das in übergeordneten Modulen Anwendung findet, damit über Module hinweg Konsistenz von Condition und Observation erhalten werden kann.
