### ISSUE TITLE
[HDB-228] - Spezifikation code.coding Element

### ISSUE THREAD

**Issue by alexzautke** [medizininformatik-initiative/kerndatensatzmodul-symptome#21]
Im Condition Profil des Basismoduls Diagnose erfolgt eine detaillierte Spezifikation der zu verwendenden Terminologien für das Element code.coding (z.B. ICD10GM inkl. System-URL). Im IG für das Erweiterungsmodul fehlt diese Spezifikation. Eine gleiche Definition wie im Basismodul wäre wünschenswert, um bei der Implementierung der entsprechenden FHIR-Ressourcen Kenntnis über die festgelegten System-URLs zu haben.

Einreichende Person: Elisa Henke

**Comment by beakmachine** [comment]
Wir haben des offen gelassen, um möglichst viele Code-Systeme zu unterstützen. Wir können hier natürlich das Model aus dem Modul Diagnose übernehmen.

**Comment by beakmachine** [comment]
Im Implementation-Guide haben wir folgenden klärenden Satz eingefügt.

"Im Gegensatz zum Modul Diagnose wird im Modul Symptom/Phänotyp kein Terminologiesystem für den Code vorgegeben, mit dem Condition kodiert werden soll, um möglichst große Flexibilität zu erlauben."
